/*
 *   AviTab - Aviator's Virtual Tablet
 *   Copyright (C) 2018-2026 Folke Will and Avitab Contributors
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *   This code AI generated by Copilot MAI-Code-1-Flash, using prompt:
 *   "Write a c++ function to unzip a zip file (specified as a std::filsystem object) 
 *   to a directory (specified as a std::filesystem object). Use the zlib/contrib/minizip library"
 *   And then some tidy-up / bug fixing / defensive programming from Gemini Flash 3.5
 */

#include <filesystem>
#include <fstream>
#include <string>
#include <vector>
#include <system_error>
#include <cstring>
#include <algorithm>

#include <contrib/minizip/unzip.h>
#include "UnzipWrapper.h"

#include "Logger.h"

bool unzip::unzip_file(const std::filesystem::path & zip_path, const std::filesystem::path & destination_dir) {
    if (!std::filesystem::exists(zip_path)) return false;

    std::error_code ec;
    auto abs_destination = std::filesystem::absolute(destination_dir, ec);
    if (ec) return false;

    std::filesystem::create_directories(abs_destination, ec);
    if (ec) return false;

    unzFile zip = unzOpen64(zip_path.string().c_str());
    if (!zip) return false;

    if (unzGoToFirstFile(zip) != UNZ_OK) {
        unzClose(zip);
        return false;
    }

    bool overall_success = true;

    do {
        char entry_name[4096] = {};
        unz_file_info file_info{};

        if (unzGetCurrentFileInfo(zip, &file_info, entry_name, sizeof(entry_name),
                                  nullptr, 0, nullptr, 0) != UNZ_OK) {
            overall_success = false;
            break; // Break the loop to close the zip cleanly
        }

        size_t len = std::strlen(entry_name);
        if (len == 0) continue; 

        std::filesystem::path out_path = abs_destination / entry_name;
        auto out_path_length = out_path.string().length();
        if (out_path_length >= 260) {
            logger::warn("Destination path length (%d) is dangerously long:", out_path_length);
            logger::warn("%s", out_path.string().c_str());
        }

        auto normal_path = std::filesystem::weakly_canonical(out_path, ec);
        if (ec) { overall_success = false; continue; }

        // Fix: Resolve symlinks in the base destination path as well to prevent false positives during extraction.
        auto canonical_destination = std::filesystem::weakly_canonical(abs_destination, ec);
        if (ec) { overall_success = false; continue; }

        // Robust Zip Slip protection using path component iterators.
        // This avoids string-based prefix matching vulnerabilities (e.g., matching "/app/target_malicious" against "/app/target").
        bool is_subpath = false;
        auto mismatch_pair = std::mismatch(canonical_destination.begin(), canonical_destination.end(), normal_path.begin(), normal_path.end());
        if (mismatch_pair.first == canonical_destination.end()) {
            is_subpath = true;
        }

        if (!is_subpath) {
            // Path escaped! Skip this file for security, but don't stop the whole extraction
            overall_success = false;
            continue;
        }

        // Check for directory entry
        if (entry_name[len - 1] == '/' || entry_name[len - 1] == '\\') {
            std::filesystem::create_directories(normal_path, ec);
            if (ec) overall_success = false;
        } else {
            // Ensure parent directory exists before writing file
            if (normal_path.has_parent_path()) {
                std::filesystem::create_directories(normal_path.parent_path(), ec);
                if (ec) {
                    overall_success = false;
                    continue; // Skip this file if directory creation failed
                }
            }

            if (unzOpenCurrentFile(zip) != UNZ_OK) {
                overall_success = false;
                continue;
            }

            std::ofstream out(normal_path, std::ios::binary);
            if (!out) {
                unzCloseCurrentFile(zip);
                overall_success = false;
                continue; // Skip individual file failures instead of killing the entire run
            }

            std::vector<char> buffer(8192);
            int read = 0;
            bool write_success = true;

            while ((read = unzReadCurrentFile(zip, buffer.data(), static_cast<unsigned>(buffer.size()))) > 0) {
                out.write(buffer.data(), read);
                if (!out) {
                    write_success = false;
                    break;
                }
            }

            out.close();
            unzCloseCurrentFile(zip);

            if (read < 0 || !write_success) {
                std::filesystem::remove(normal_path, ec); 
                overall_success = false;
            }
        }
    } while (unzGoToNextFile(zip) == UNZ_OK);

    unzClose(zip);
    return overall_success;
}
